# Generated by Django 3.0.5 on 2020-04-16 17:01

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnswersKey',
            fields=[
                ('a', models.AutoField(primary_key=True, serialize=False)),
                ('lvl_1', models.CharField(blank=True, max_length=200, null=True)),
                ('lvl_2', models.CharField(blank=True, max_length=200, null=True)),
                ('lvl_3', models.CharField(blank=True, max_length=200, null=True)),
                ('lvl_4', models.ImageField(blank=True, null=True, upload_to='')),
                ('lvl_5', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('p', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('usn', models.CharField(max_length=30, unique=True)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=10)),
                ('phone_no', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')])),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Submissions',
            fields=[
                ('a', models.AutoField(primary_key=True, serialize=False)),
                ('l1', models.CharField(blank=True, max_length=200, null=True)),
                ('l2', models.CharField(blank=True, max_length=200, null=True)),
                ('l3', models.CharField(blank=True, max_length=200, null=True)),
                ('l4', models.ImageField(blank=True, null=True, upload_to='')),
                ('l5', models.CharField(blank=True, max_length=200, null=True)),
                ('l1_time', models.DateTimeField(blank=True, null=True)),
                ('l2_time', models.DateTimeField(blank=True, null=True)),
                ('l3_time', models.DateTimeField(blank=True, null=True)),
                ('l4_time', models.DateTimeField(blank=True, null=True)),
                ('l5_time', models.DateTimeField(blank=True, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
