# Generated by Django 3.0.4 on 2020-04-26 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissions',
            name='l6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='l6_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submissions',
            name='phase_2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
