# Generated by Django 3.0.4 on 2020-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tsite', '0002_auto_20200426_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerskey',
            name='lvl_6',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
